### ISSUE TITLE
함수 매개변수가 무엇을 나타내는지

### ISSUE THREAD

**Issue by wlghks0723** [xinfolab/open-source-subject#17]
int64_t file_time_delta_sec(_In_ const PFILETIME ftl, _In_ const PFILETIME ftr)

해당 위 함수의 ftl,ftr의 매개변수가 무엇을 나타내는지를 모르겠음

**Comment by recotaru** [comment]
ftl -> LowDataTime
ftr -> HighDataTime

https://msdn.microsoft.com/ko-kr/library/windows/desktop/ms724284(v=vs.85).aspx 참고

**Comment by xinfolab** [comment]
해당 함수는 아래 함수와 연결되어 있음  
```
uint64_t file_time_to_int(_In_ const PFILETIME file_time)
{
	return ((LARGE_INTEGER*)file_time)->QuadPart;
}
```

+ ftl 약자는 file time left, ftr은 file time right
+ 두 변수의 시간차를 반환함. 
+ ftr - ftl = 시간의 차이
+ 참고
https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(MINWINDEF%2FPFILETIME);k(PFILETIME);k(DevLang-C%2B%2B);k(TargetOS-Windows)&rd=true
