### ISSUE TITLE
작업남은 함수 19개

### ISSUE THREAD

**Issue by wlghks0723** [xinfolab/open-source-subject#24]
bool dump_boot_area()
bool get_temp_dirW(_Out_ std::wstring& temp_dir);
bool get_temp_dirA(_Out_ std::string& temp_dir);
bool get_module_path(_In_ const wchar_t* module_name, _Out_ std::wstring& module_path);
bool get_current_module_path(_Out_ std::wstring& module_path);
bool get_current_module_dir(_Out_ std::wstring& module_dir);
bool get_current_module_file(_Out_ std::wstring& module_file);
std::wstring get_module_pathEx(_In_ const wchar_t* module_name);
std::wstring get_module_dirEx(_In_ const wchar_t* module_name);
std::wstring get_current_module_pathEx();
std::wstring get_current_module_dirEx();
std::wstring get_current_module_fileEx();
std::wstring device_name_from_nt_name(_In_ const wchar_t* nt_name);
std::wstring device_name_from_nt_name(_In_ const wchar_t* nt_name);
std::wstring file_name_from_file_path(_In_ const wchar_t* file_path);
typedef bool (WINAPI *fnFindFilesCallback)(_In_ DWORD_PTR tag, _In_ const wchar_t* path);
BOOL WUGetCurrentDirectoryW(IN OUT std::wstring& CurrentDir);
BOOL WUGetCurrentDirectoryA(IN OUT std::string& CurrentDir);
FILETIME add_day_to_file_time(_In_ const PFILETIME file_time, _In_ int32_t day);

**Comment by wlghks0723** [comment]
20개

**Comment by xinfolab** [comment]
#27 merge 완료
