### ISSUE TITLE
12월 7일까지 pdf로 변환해야한다.

### ISSUE THREAD

**Issue by xinfolab** [xinfolab/open-source-subject#34]
변환 후 git에 올려야한다.

**Comment by xinfolab** [comment]
1. 오픈 소스 SW 선택의 이유 및 개요 (10)
2. 오픈 소스 SW에 대한 각 기능별 설명 (10)
3. 오픈 소스 SW 사용 설명에 대한 쉬운 이해가 가능한지 (10)
4. 사용 설명서 작성 중 발견한 오픈 소스 SW의 버그 및 원인 또는 사용 설명서 작성 중 느낀 기능 향상을 위한 제안 (10)
5. 각 팀원 별 협업을 증명할 자료 첨부(예: GitHub에 나와 있는 협업 히스토리) (20)

**Comment by wlghks0723** [comment]
vs code 파일 자신 개임 md파일 pdf로 변경하는 것인지 ??

**Comment by xinfolab** [comment]
이건 완료 했을 경우 pdf 로 변환임~

**Comment by wlghks0723** [comment]
기능별 설명은 vscode있는거 쓰면되고 // 이유와 개요는 작성하면되는거고 /// 작성중 느낀 기능향상을 위한 제안 (작성)해야되고//// 그럼 크게 작성할게 이유,개요,기능향상을위한 제안이고 협업증빙 자료는 히스토리랑 이슈랑 그정도 하면되는 ?

**Comment by xinfolab** [comment]
#33 도 부족한 부분 채워야하고, 저기 있는 5가지도 채워야하고,,,
내가 일이 많아서 아직 못하고 있음.
날을 새서라도 이번주 주말안에 끝내고 최종 md를 올리겠음.
채웠으면 하는 부분을 추가로 말해주거나 수정해서 올리면 될듯.
그리고 세명다 ok 했을 경우 pdf 로 변환

**Comment by xinfolab** [comment]
#40 변환 완료 및 push
